
train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: True
  pin_memory: True
  num_workers: 4

  dataset:
    _target_: echocem.data.data.CemDataset
    images_path: data/processed/X_train/images
    annotations_path: data/processed/X_train/annotations
    crop_size: [272, 272]
    excluded_wells: []
    file_format: 'processed'

  
validation_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  shuffle: False
  pin_memory: True
  num_workers: 2

  # validation is based on the raw data (je me souviens plus pourquoi)
  dataset:
    _target_: echocem.data.data.CemDataset
    images_path: data/raw/X_train/images
    annotations_path: data/raw/X_train/patch_annotations
    crop_size: null
    excluded_wells: []
    file_format: 'raw'
