
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  shuffle: True
  pin_memory: True
  num_workers: 8

  dataset:
    _target_: echocem.data.data.CemDataset
    images_path: data/processed/X_train/images
    annotations_path: data/processed/X_train/annotations
    crop_size: [256, 272]
    excluded_wells: [3, 4]
    preload_data: True
    cache_size: 1000