trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 1000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 5
  accelerator: gpu
  devices: 1

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      every_n_epochs: 1
      save_top_k: 1
      save_last: true
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      monitor: step
      mode: max
      every_n_epochs: 10
      save_top_k: -1
      save_last: false
    - _target_: echocem.callback.progress.ProgressLogger
      precision: 3
    - _target_: echocem.callback.tqdmbar.TQDMProgressBar

  logger:
    - _target_: pytorch_lightning.loggers.WandbLogger
      project: "CemSeg"  # Group experiments under this project
      name: "v0"             # Optional: give specific name to this run
      save_dir: "wandb/"          # Optional: where to store wandb files
      log_model: false             # Optional: log model checkpoints
